# Generated by Django 4.2 on 2026-04-07 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('Sales', 'Sales'), ('Accounting', 'Accounting'), ('Finance', 'Finance'), ('Delivery', 'Delivery'), ('Warehouse', 'Warehouse'), ('Management', 'Management')], max_length=50)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Sales Rep', 'Sales Rep'), ('Accountant', 'Accountant'), ('Finance Officer', 'Finance Officer'), ('Driver', 'Driver'), ('Warehouse Staff', 'Warehouse Staff'), ('Dispatcher', 'Dispatcher')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('driver_license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('max_load_capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_for_delivery', models.BooleanField(default=True)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('truck_number', models.CharField(max_length=50, unique=True)),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_load_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_operational', models.BooleanField(default=True)),
                ('last_known_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('last_known_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trucks', to='employees.employee')),
            ],
            options={
                'db_table': 'trucks',
                'ordering': ['truck_number'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('order_id', models.CharField(max_length=255)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_location', models.TextField(blank=True)),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('delivery_photo', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_deliveries', to='employees.employee')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='employees.employee')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='employees.truck')),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
