from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_portal_root, name='admin_portal_root'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('products/', views.products_page, name='products'),
    path('orders/', views.orders_page, name='orders'),
    path('orders/<str:order_id>/assign/', views.create_assignment, name='create_assignment'),
    path('orders/<str:order_id>/history/', views.get_order_history, name='order_history'),
    path('requests/<str:request_id>/update/', views.update_request_status, name='update_request_status'),
    path('employees/', views.employees_page, name='employees'),
    path('employees/create/', views.employee_create_page, name='employee_create_page'),
    path('employees/<str:employee_id>/edit/', views.employee_edit_page, name='employee_edit_page'),
    path('employees/<str:employee_id>/delete/', views.employee_delete_page, name='employee_delete_page'),
    path('trucks/', views.trucks_page, name='trucks'),
    path('trucks/create/', views.truck_create_page, name='truck_create_page'),
    path('trucks/<str:truck_id>/edit/', views.truck_edit_page, name='truck_edit_page'),
    path('trucks/<str:truck_id>/delete/', views.truck_delete_page, name='truck_delete_page'),
    path('deliveries/', views.deliveries_page, name='deliveries'),
    path('notifications/', views.notifications_page, name='notifications'),
    path('reports/', views.reports_page, name='reports'),
    path('api/employees/', views.api_employees, name='api_employees'),
    path('api/trucks/', views.api_trucks, name='api_trucks'),
    path('orders/<str:order_id>/assign/', views.create_assignment, name='create_assignment'),
    path('orders/<str:order_id>/history/', views.get_order_history, name='order_history'),
    path('requests/<str:request_id>/update/', views.update_request_status, name='update_request_status'),
    path('api/deliveries/', views.api_deliveries, name='api_deliveries'),
    path('products/', views.products_page, name='products'),
    path('products/create/', views.product_create_page, name='product_create'),
    path('products/<str:product_id>/', views.product_detail_page, name='product_detail'),
    path('products/<str:product_id>/edit/', views.product_edit_page, name='product_edit'),
    path('products/<str:product_id>/delete/', views.product_delete_page, name='product_delete'),
]